import "./globals.css";
import Nav from "./Nav";
import { Montserrat } from "next/font/google";
import QueryWrapper from "./auth/QueryWrapper";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`mx-4 md:mx-36 xl:mx-96 ${montserrat.className} bg-gray-200`}
      >
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
